/********************************************************************************/
/*  StePS - STEreographically Projected cosmological Simulations                */
/*    Copyright (C) 2017-2026 Gabor Racz                                        */
/*                                                                              */
/*    This program is free software; you can redistribute it and/or modify      */
/*    it under the terms of the GNU General Public License as published by      */
/*    the Free Software Foundation; either version 2 of the License, or         */
/*    (at your option) any later version.                                       */
/*                                                                              */
/*    This program is distributed in the hope that it will be useful,           */
/*    but WITHOUT ANY WARRANTY; without even the implied warranty of            */
/*    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             */
/*    GNU General Public License for more details.                              */
/********************************************************************************/

/*  pds_group.h — Mathematical primitives for Poincaré Dodecahedral Space (PDS)
 *
 *  PDS = S³ / I*  where I* is the binary icosahedral group (120 unit quaternions).
 *
 *  Particle positions in PDS are represented as unit quaternions
 *  q = (q0, q1, q2, q3) ∈ S³ ⊂ ℝ⁴.  The fundamental domain is a spherical
 *  dodecahedron with its centre at the north pole  e₀ = (1, 0, 0, 0).
 *
 *  I* is generated by two unit quaternions (group presentation s³ = t⁵ = (st)² = −1):
 *      s = ½(1, 1, 1, 1)                              [order 6, s³ = −1]
 *      t = ½(τ, 1/τ, 1, 0),  τ = (1+√5)/2            [order 10, t⁵ = −1]
 *
 *  I* has order 120.  Both +q and −q are distinct elements (the center {±1}
 *  is the subgroup {+e, −e}).  Do NOT conflate +q with −q for group elements.
 *
 *  The group is generated at runtime by BFS closure under multiplication from
 *  {s, s⁻¹, t, t⁻¹}.  This is self-validating: the BFS aborts if the count
 *  differs from 120.
 *
 *  USAGE
 *  -----
 *  Call pds_init() once at program startup (before any PDS force or boundary
 *  calculation).  All other functions are then safe to call.
 *
 *  GEOMETRY CONVENTIONS
 *  --------------------
 *  - S³ has unit radius (particles stored as unit 4-vectors).
 *  - Geodesic distance: χ(p,q) = arccos(p·q) ∈ [0, π].
 *  - Physical distances scale as r = R_curv · χ.
 *  - Force kernels (per unit source mass, G = 1, no 4π factor):
 *      pds_green()             — bare 1/(R² sin²χ) (isolated point mass)
 *      pds_green_compensated() — [1 − V(χ)/V_S³]/(R² sin²χ) (point mass +
 *        uniform negative background; see Lachieze-Rey & Luminet 1995,
 *        Phys. Rep. 254).  The COMPENSATED kernel must be used when summing
 *        over the I* images: I* is closed under negation and the bare kernel
 *        satisfies G(π−χ) = G(χ) with opposite tangent directions, so the
 *        bare force from the full 120-image system cancels identically.
 *  - Fundamental domain: Voronoi cell of e₀ under I* action,
 *    i.e., q ∈ domain ⟺ q[0] = max_{g ∈ I*}(q·g) (real-part condition,
 *    NOT absolute value — since −e₀ ∈ I* this gives q[0] ≥ 0 automatically).
 *
 *  References:
 *    Luminet, J.-P. et al. (2003). Nature 425, 593. arXiv:astro-ph/0310253
 *    Weeks, J. R. (2001). "The Shape of Space" (2nd ed.), CRC Press.
 *    Riazuelo, A. et al. (2004). Phys. Rev. D 69, 103518.
 */

#ifndef PDS_GROUP_H
#define PDS_GROUP_H

#include <math.h>
#include <stdio.h>
#include <stdlib.h>

/* ─── Constants ────────────────────────────────────────────────────────────── */

/* Golden ratio and its reciprocal */
#define PDS_TAU   1.6180339887498948482   /* (1 + sqrt(5)) / 2 */
#define PDS_ITAU  0.6180339887498948482   /* 1/tau = tau − 1   */

/* Number of I* group elements */
#define PDS_N_ISTAR 120

/* Componentwise equality tolerance for unit quaternions */
#define PDS_QUAT_EPS 1e-9

/* ─── Group storage ─────────────────────────────────────────────────────────── */

/* The 120 unit quaternions of I*, filled by pds_init().
 * Each row is (q0, q1, q2, q3).  Do NOT modify after init.
 *
 * 'inline' (C++17) gives a single shared definition across all translation
 * units.  Do NOT use 'static' here — that would give each .cc file its own
 * private zero-filled copy, causing pds_wrap() to see uninitialized data
 * when called from a different TU than the one that ran pds_init(). */
inline double PDS_I_STAR[PDS_N_ISTAR][4] = {};
inline int    PDS_ISTAR_READY = 0;

/* ─── Quaternion arithmetic ────────────────────────────────────────────────── */

/* Hamilton product: r = p ⊗ q */
static inline void pds_quat_mult(const double p[4], const double q[4], double r[4])
{
    r[0] = p[0]*q[0] - p[1]*q[1] - p[2]*q[2] - p[3]*q[3];
    r[1] = p[0]*q[1] + p[1]*q[0] + p[2]*q[3] - p[3]*q[2];
    r[2] = p[0]*q[2] - p[1]*q[3] + p[2]*q[0] + p[3]*q[1];
    r[3] = p[0]*q[3] + p[1]*q[2] - p[2]*q[1] + p[3]*q[0];
}

/* Conjugate (= inverse for unit quaternions): cq = (q0, −q1, −q2, −q3) */
static inline void pds_quat_conj(const double q[4], double cq[4])
{
    cq[0] =  q[0];  cq[1] = -q[1];  cq[2] = -q[2];  cq[3] = -q[3];
}

/* 4D dot product (Euclidean inner product of the coordinate vectors) */
static inline double pds_dot4(const double p[4], const double q[4])
{
    return p[0]*q[0] + p[1]*q[1] + p[2]*q[2] + p[3]*q[3];
}

/* Normalise a quaternion in place (corrects floating-point drift) */
static inline void pds_normalise(double q[4])
{
    double n = sqrt(q[0]*q[0] + q[1]*q[1] + q[2]*q[2] + q[3]*q[3]);
    q[0] /= n;  q[1] /= n;  q[2] /= n;  q[3] /= n;
}

/* Componentwise equality of two unit quaternions.
 * NOTE: +q and −q are DIFFERENT elements of I*, do not use |dot|≈1. */
static inline int pds_quat_same(const double p[4], const double q[4])
{
    return (fabs(p[0]-q[0]) < PDS_QUAT_EPS
         && fabs(p[1]-q[1]) < PDS_QUAT_EPS
         && fabs(p[2]-q[2]) < PDS_QUAT_EPS
         && fabs(p[3]-q[3]) < PDS_QUAT_EPS);
}

/* ─── Group generation by BFS ──────────────────────────────────────────────── */

/*  Verified generators of I* satisfying s³ = t⁵ = (st)² = −1:
 *    s = ½(1,1,1,1)         — one can verify s³ = (−1,0,0,0) = −e
 *    t = ½(τ,1/τ,1,0)      — |t|² = (τ²+1/τ²+1)/4 = 1 (using τ²+1/τ²=3) */
static const double PDS_GEN[4][4] = {
    {  0.5,            0.5,           0.5,  0.5  },   /* s    */
    {  0.5,           -0.5,          -0.5, -0.5  },   /* s⁻¹  */
    {  PDS_TAU*0.5,  PDS_ITAU*0.5,   0.5,  0.0  },   /* t    */
    {  PDS_TAU*0.5, -PDS_ITAU*0.5,  -0.5,  0.0  },   /* t⁻¹  */
};

/*  Generate all 120 I* elements by BFS closure under multiplication.
 *  Uses a fixed-size work queue (1200 slots — well above the worst-case). */
static inline void pds_generate_group(void)
{
    /* Work queue: holds elements pending expansion.  Any element may appear
     * multiple times; duplicates are filtered when popped. */
    double  wq[1200][4];
    int     wq_head = 0, wq_tail = 0;
    int     found   = 0;

    /* Seed with the identity element */
    wq[wq_tail][0] = 1.0;  wq[wq_tail][1] = 0.0;
    wq[wq_tail][2] = 0.0;  wq[wq_tail][3] = 0.0;
    wq_tail++;

    while(wq_head < wq_tail)
    {
        double cur[4];
        for(int k = 0; k < 4; k++) cur[k] = wq[wq_head][k];
        wq_head++;

        /* Skip if already in PDS_I_STAR */
        int dup = 0;
        for(int i = 0; i < found; i++) {
            if(pds_quat_same(cur, PDS_I_STAR[i])) { dup = 1; break; }
        }
        if(dup) continue;
        if(found >= PDS_N_ISTAR) continue;

        /* Accept this element */
        for(int k = 0; k < 4; k++) PDS_I_STAR[found][k] = cur[k];
        found++;

        /* Enqueue products with each generator */
        for(int g = 0; g < 4; g++) {
            if(wq_tail >= 1200) {
                /* Expand right-multiply: cur ⊗ gen[g] */
                continue;  /* drop — element reachable by another path */
            }
            double nr[4];
            pds_quat_mult(cur, PDS_GEN[g], nr);
            pds_normalise(nr);

            /* Only enqueue if not already found */
            int seen = 0;
            for(int i = 0; i < found; i++) {
                if(pds_quat_same(nr, PDS_I_STAR[i])) { seen = 1; break; }
            }
            if(!seen) {
                for(int k = 0; k < 4; k++) wq[wq_tail][k] = nr[k];
                wq_tail++;
            }
        }
    }

    if(found != PDS_N_ISTAR) {
        fprintf(stderr,
            "pds_generate_group: FATAL — generated %d elements, expected %d.\n"
            "  BFS queue overflowed or generators are incorrect.\n",
            found, PDS_N_ISTAR);
        exit(EXIT_FAILURE);
    }
}

/* ─── Initialisation ──────────────────────────────────────────────────────── */

/*  pds_init() — must be called once before any other PDS function.
 *  Safe to call multiple times (no-op after first call). */
static inline void pds_init(void)
{
    if(PDS_ISTAR_READY) return;
    pds_generate_group();
    PDS_ISTAR_READY = 1;
    printf("PDS: Binary icosahedral group I* generated (%d elements).\n", PDS_N_ISTAR);
}

/* ─── Geodesic distance on S³ ──────────────────────────────────────────────── */

/*  Geodesic distance χ ∈ [0, π] between unit quaternions p and q on S³.
 *
 *    χ(p, q) = arccos(p · q)
 *
 *  Physical separation: r = R_curv · χ.
 *
 *  Note: χ(p, −p) = π (antipodal points).  In PDS, p and −p are the SAME
 *  physical point (since −1 ∈ I* identifies them), but they are DISTINCT
 *  I* group elements. */
static inline double pds_chi(const double p[4], const double q[4])
{
    double d = pds_dot4(p, q);
    if(d >  1.0) d =  1.0;  /* guard floating-point overshoot */
    if(d < -1.0) d = -1.0;
    return acos(d);
}

/* ─── Curved-space force magnitude on S³ ───────────────────────────────────── */

/*  Gravitational force per unit source mass on S³ (curvature radius R_curv).
 *
 *  Derived from Gauss's law on S³: the area of a geodesic sphere at distance χ
 *  is 4π R² sin²χ, giving force magnitude F = G M / (4π R² sin²χ).  With G=1
 *  (StePS internal units) and absorbing the 4π into the Poisson convention:
 *
 *    pds_green(χ, R) = 1 / (R² sin²χ)
 *
 *  This is the scalar magnitude of the acceleration on a test particle due to a
 *  unit-mass source at geodesic distance χ.  The force vector is:
 *    F = M_source * pds_green(χ, R) * tangent(p → q_source)
 *
 *  Flat-space limit (χ → 0, r = Rχ):  pds_green → 1/r²  ✓
 *
 *  Returns 0 at χ = 0 (no self-force) or χ ≥ π (antipodal, force is zero by
 *  symmetry of the closed S³). */
static inline double pds_green(double chi, double R_curv)
{
    if(chi < 1e-12 || chi > M_PI - 1e-12) return 0.0;
    double s = sin(chi);
    return 1.0 / (R_curv * R_curv * s * s);
}

/*  Background-compensated force kernel on S³ (per unit source mass):
 *
 *    pds_green_compensated(χ, R) = [1 − V(χ)/V_S³] / (R² sin²χ),
 *    V(χ)/V_S³ = (2χ − sin 2χ) / (2π)
 *
 *  This is the force of a point mass plus a uniform NEGATIVE background of
 *  equal total mass.  In comoving cosmological simulations the homogeneous
 *  mean density is already accounted for by the Friedmann expansion, so
 *  peculiar forces must be sourced by fluctuations only — the exact analogue
 *  of dropping the k = 0 mode in T³ Ewald summation.
 *
 *  Crucially, the compensation breaks the antipodal degeneracy of the bare
 *  kernel: with pds_green() the force from the full 120-image I* system of
 *  any source is IDENTICALLY ZERO (images come in ±g pairs with equal bare
 *  magnitudes and opposite directions).  The compensated kernel yields the
 *  finite, physical peculiar force.
 *
 *  Limits: → 1/r² (r = Rχ) as χ → 0;  → 0 smoothly (∝ π−χ) at the antipode. */
static inline double pds_green_compensated(double chi, double R_curv)
{
    if(chi < 1e-12 || chi > M_PI - 1e-12) return 0.0;
    double s = sin(chi);
    double frac = (2.0*chi - sin(2.0*chi)) / (2.0*M_PI);
    return (1.0 - frac) / (R_curv * R_curv * s * s);
}

/* ─── Fundamental domain test and boundary wrapping ────────────────────────── */

/*  Test whether unit quaternion q lies in the fundamental domain of S³/I*.
 *
 *  The domain is the Voronoi cell of e₀ = (1,0,0,0) under I*:
 *    q ∈ domain  ⟺  q·e₀ ≥ q·g  for all g ∈ I*
 *    ⟺  q[0] ≥ pds_dot4(q, g)   for all g ∈ I*
 *    ⟺  q[0] = max_{g ∈ I*} pds_dot4(q, g)
 *
 *  Since −e ∈ I* and pds_dot4(q, −e) = −q[0], the condition automatically
 *  ensures q[0] ≥ 0.
 *
 *  Returns 1 if in domain, 0 otherwise. */
static inline int pds_in_domain(const double q[4])
{
    double d0 = q[0];  /* q · e₀ = q[0] */
    for(int g = 0; g < PDS_N_ISTAR; g++) {
        if(pds_dot4(q, PDS_I_STAR[g]) > d0 + PDS_QUAT_EPS) return 0;
    }
    return 1;
}

/*  Map unit quaternion q to its canonical representative in the fundamental domain.
 *
 *  Algorithm:
 *    1. g* = argmax_{g ∈ I*} pds_dot4(q, g)   (find nearest domain centre)
 *    2. q' = conj(g*) ⊗ q                       (left-multiply by (g*)⁻¹)
 *
 *  After wrapping, q'[0] ≥ 0 (canonical sign convention for PDS).
 *  Writes result to q_out[4]; q and q_out may alias. */
static inline void pds_wrap(const double q[4], double q_out[4])
{
    if(!PDS_ISTAR_READY) pds_init();
    int    best   = 0;
    double best_d = pds_dot4(q, PDS_I_STAR[0]);
    for(int g = 1; g < PDS_N_ISTAR; g++) {
        double d = pds_dot4(q, PDS_I_STAR[g]);
        if(d > best_d) { best_d = d; best = g; }
    }
    double gconj[4];
    pds_quat_conj(PDS_I_STAR[best], gconj);
    double tmp[4];
    pds_quat_mult(gconj, q, tmp);
    pds_normalise(tmp);
    for(int k = 0; k < 4; k++) q_out[k] = tmp[k];
}

/* ─── Stereographic velocity transformation under face identification ───────── */

/*  Transform the stereographic velocity when pds_wrap maps q_in → q_out.
 *
 *  The stereographic velocity v = dx/dt lives in the tangent space of the
 *  stereographic projection.  When pds_wrap applies the isometry
 *      q_out = ḡ · q_in   (ḡ = conj(g*), the wrapping group element)
 *  the velocity must be parallel-transported through that isometry:
 *
 *    u      = [∂q/∂x]|_{x_in} · v_in    (lift v to S³ tangent at q_in via
 *                                         Jacobian of the inverse stereo map)
 *    w      = ḡ · u                       (transport by the quaternion isometry;
 *                                         ḡ is recovered as q_out · conj(q_in))
 *    v_out  = [∂x/∂q]|_{q_out} · w       (project w back to R³ via Jacobian of
 *                                         the forward stereo map at q_out)
 *
 *  The composition [∂x/∂q] ∘ L_ḡ ∘ [∂q/∂x] is the correct 3×3 Jacobian of the
 *  map x_out = f(ḡ · f⁻¹(x_in)).  For in-domain particles (g* = identity) it
 *  reduces to the identity.
 *
 *  v[] is modified in place.  R = PDS_R_CURV.
 *
 *  Only call this when pds_wrap actually changed the quaternion
 *  (!pds_quat_same(q_in, q_out)); it is mathematically the identity otherwise,
 *  but calling it unconditionally wastes time and may accumulate float errors.
 */
static inline void pds_stereo_vel_transform(
        const double q_in[4],  const double q_out[4],
        const double x_in[3],  const double x_out[3],
        double v[3], double R)
{
    /* Step 1 — u = (∂q/∂x)|_{x_in} · v  (inverse-stereo Jacobian) */
    double r2 = x_in[0]*x_in[0] + x_in[1]*x_in[1] + x_in[2]*x_in[2];
    double D  = R*R + r2;
    double D2 = D*D;
    double xv = x_in[0]*v[0] + x_in[1]*v[1] + x_in[2]*v[2];
    double u[4];
    u[0] = -4.0*R*R*xv / D2;
    u[1] =  2.0*R*(D*v[0] - 2.0*x_in[0]*xv) / D2;
    u[2] =  2.0*R*(D*v[1] - 2.0*x_in[1]*xv) / D2;
    u[3] =  2.0*R*(D*v[2] - 2.0*x_in[2]*xv) / D2;

    /* Step 2 — w = ḡ · u,   ḡ = q_out · conj(q_in) */
    double qic[4];  pds_quat_conj(q_in, qic);
    double gb[4];   pds_quat_mult(q_out, qic, gb);   /* gb = ḡ */
    double w[4];    pds_quat_mult(gb, u, w);

    /* Step 3 — v_out = (∂x/∂q)|_{q_out} · w  (forward-stereo Jacobian) */
    double s = 1.0 / (1.0 + q_out[0]);
    v[0] = s*(R*w[1] - x_out[0]*w[0]);
    v[1] = s*(R*w[2] - x_out[1]*w[0]);
    v[2] = s*(R*w[3] - x_out[2]*w[0]);
}

/* ─── Force direction on S³ ────────────────────────────────────────────────── */

/*  Unit tangent vector at p pointing toward q along the geodesic (force direction).
 *
 *    t = (q − (p·q) p) / |q − (p·q) p|
 *
 *  This is perpendicular to p and points "toward q" on S³.
 *  If p = ±q, t_out is set to zero. */
static inline void pds_force_direction(const double p[4], const double q[4], double t_out[4])
{
    double d = pds_dot4(p, q);
    double len2 = 0.0;
    for(int k = 0; k < 4; k++) { t_out[k] = q[k] - d*p[k];  len2 += t_out[k]*t_out[k]; }
    if(len2 < 1e-24) { for(int k = 0; k < 4; k++) t_out[k] = 0.0; return; }
    double inv_len = 1.0 / sqrt(len2);
    for(int k = 0; k < 4; k++) t_out[k] *= inv_len;
}

/* ─── Image enumeration ─────────────────────────────────────────────────────── */

/*  Compute the g-th I* image of position q: q_img = PDS_I_STAR[g_idx] ⊗ q */
static inline void pds_apply_group_element(int g_idx, const double q[4], double q_img[4])
{
    pds_quat_mult(PDS_I_STAR[g_idx], q, q_img);
}

#endif /* PDS_GROUP_H */
